all:
  sf_guard_plugin:
    success_signin_url:           dashboard/index
    success_signout_url:          sfGuardAuth/signin
    remember_key_expiration_age:  2592000 # 30 jours
    remember_cookie_name:         sfBootstrapRememberMe # @EDIT

  recaptcha:
    public_key:                   6LdAxdUSAAAAA...  # @EDIT
    private_key:                  6LdAxdUSAAAAA...  # @EDIT