all:
  sf_guard_plugin:
    success_signin_url:           dashboard/index
    success_signout_url:          dashboard/index
    remember_key_expiration_age:  2592000 # 30 jours
    remember_cookie_name:         e3RememberMe
  sf_less_plugin:
    compile:           false
    
dev:
  sf_less_plugin:
    compile:            true
    use_js:             false
    use_compression:    false