prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
  mailer:
    param:
      delivery_strategy: realtime
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      transport:
        class: Swift_SmtpTransport
        param:
          host:       localhost
          port:       25
          encryption: ~
          username:   ~
          password:   ~
  response:
    class: sfWebResponse
    param:
      send_http_headers: false

dev:
  mailer:
    param:
      delivery_strategy: single_address # Redirige tous les envois de mail de l'appli vers l'adresse renseignée ci-dessous
      delivery_address:  mon_adresse@gmail.com
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp.gmail.com
          port:       465
          encryption: ssl
          username:   mail@mail.com @EDIT
          password:   mdp           @EDIT
  logger:
    class: sfAggregateLogger
    param:
      level: debug
      loggers:
        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: debug
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: sfWebDebug

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
