demo:
  url: /demonstration
  param: { module: dashboard, action: demo }
  
icon:
  url: /icones
  param: { module: dashboard, action: icon }
  
## User routes ##

user_profile:
  url: /mon-compte
  param: { module: account, action: show }

user_edit:
  url: /mon-compte/edition
  param: { module: account, action: edit }

## Default routes ##

sf_guard_signout:
  url:   /deconnexion
  param: { module: sfGuardAuth, action: signout }

homepage:
  url:   /
  param: { module: dashboard, action: index }