all:
  .actions:
    login_module:           sfGuardAuth
    login_action:           signin
     
    secure_module:          sfGuardAuth
    secure_action:          secure

    error_404_module:       main
    error_404_action:       error404