default:
  http_metas:
    content-type: text/html

  metas:
    title:        sfBootstrap # @EDIT
    description:  Bootstrap Symfony/Twitter 2.0 # @EDIT
    language:     fr

  stylesheets:
    - twitter/bootstrap.css
    - twitter/responsive.css
    - jq-theme/jquery-ui-1.8.16.custom.css
    - file-input/enhanced.css
    - style.css
    
  javascripts:
    - jq-theme/jquery-ui-1.8.23.custom.min.js
    - twitter/bootstrap-transition.js
    - twitter/bootstrap-affix.js
    - twitter/bootstrap-alert.js
    - twitter/bootstrap-button.js
    - twitter/bootstrap-collapse.js
    - twitter/bootstrap-dropdown.js
    - twitter/bootstrap-modal.js
    - twitter/bootstrap-tooltip.js
    - twitter/bootstrap-popover.js
    - twitter/bootstrap-tab.js
    - file-input/enhance.min.js
    - file-input/fileinput.jquery.js
    - dataTables/jquery.dataTables.min.js
    - script.js

  has_layout:     true
  layout:         layout