dev:
  propel:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=sfBootstrap' # @EDIT
      username: sfBootstrap  # @EDIT
      password: null
      encoding: # On laisse l'encodage vide pour les versions de PHP inférieures à 5.3.6, pour les version supérieures mettre utf8 @EDIT
      persistent: true
      pooling: true
      queries: { value: 'SET NAMES UTF8;' }