propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
    
  sf_guard_user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    id:                      ~
    user_id:                 { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    gender:                  { type: integer }
    first_name:              { type: varchar(45) }
    last_name:               { type: varchar(45) }
    email:                   { type: varchar(100), index: unique }
    image_path:              { type: varchar(255) }