prod:
  .settings:
    no_script_name:         true   # Pas de frontend_dev.php dans l'url
    logging_enabled:        false  # Absence de log pour petit gain de performance

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            81daab74248c7a9ea2b510650499ad693f85963a # @EDIT
    
    # Set default Timezone
    default_timezone:       Europe/Paris
    i18n:                   on
    default_culture:        fr

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    # load Jquery core
    jquery_core:            jquery-1.7.1.min.js
    jquery_web_dir:         /sfJqueryReloadedPlugin
    
    enabled_modules:        [default, sfGuardAuth, sfGuardRegister, sfGuardForgotPassword]
    standard_helpers:       [Partial, jQuery, Date, LinkToIco]
    
    charset:                utf-8
    
